### ISSUE TITLE
Events: "Opslaan en opnieuw bewerken" gaat stuk

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#230]
In GitLab by gerlings on Dec 9, 2016, 13:38

Dit is al de tweede keer dat ik een event volledig invul en alles kwijt ben, omdat ik mijn werk op wil slaan. [frustration intensifies] 
Hoewel er bij staat dat jullie er nu van op de hoogte zijn, zou ik dit graag ook in een issue hebben, zodat ik weet wanneer het is opgelost.

Alvast bedankt!

```
Traceback: 

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner 
39. response = get_response(request) 

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response 
187. response = self.process_exception_by_middleware(e, request) 

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response 
185. response = wrapped_callback(request, *callback_args, **callback_kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in wrapper 
544. return self.admin_site.admin_view(view)(*args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view 
149. response = view_func(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func 
57. response = view_func(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/sites.py" in inner 
211. return view(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in add_view 
1509. return self.changeform_view(request, None, form_url, extra_context) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper 
67. return bound_func(*args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view 
149. response = view_func(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func 
63. return func.__get__(self, type(self))(*args2, **kwargs2) 

File "/usr/local/lib/python3.5/contextlib.py" in inner 
30. return func(*args, **kwds) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in changeform_view 
1441. if form.is_valid(): 

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in is_valid 
169. return self.is_bound and not self.errors 

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in errors 
161. self.full_clean() 

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in full_clean 
370. self._clean_fields() 

File "/usr/local/lib/python3.5/site-packages/django/forms/forms.py" in _clean_fields 
388. value = field.clean(value) 

File "/usr/local/lib/python3.5/site-packages/django/forms/fields.py" in clean 
158. value = self.to_python(value) 

File "/usr/local/lib/python3.5/site-packages/django/forms/models.py" in to_python 
1220. value = self.queryset.get(**{key: value}) 

File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py" in get 
389. (self.model._meta.object_name, num) 

Exception Type: MultipleObjectsReturned at /admin/events/event/add/ 
Exception Value: get() returned more than one Committee -- it returned 2! 
Request information: 
USER: fgerlings
```

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 9, 2016, 14:05

Wat doe je precies? Ik probeer het al even te reproduceren

**Comment by thaliawww-service** [comment]
In GitLab by gerlings on Dec 9, 2016, 14:16

Ik vul in alle verplichte velden "asdf" /"vandaag"/"nu" in.
Bij organisator lukt het me om alles op te slaan wanneer ik er "eerstejaarscie" invul.
Bij "onderwijscie" gaat hij stuk (bij beiden varianten, dus de "voorzitter" en de "lid" variant) #majorLead
Als je wil kan ik het komende uur nog langskomen in Merc om het te reproducen.

GL debugging!

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 9, 2016, 15:27

Dit lijkt een afgeleide van #203. Ik heb je duplicaat verwijderd, werkt het nu wel voor je?

**Comment by thaliawww-service** [comment]
In GitLab by gerlings on Dec 9, 2016, 15:50

:/ You have been notified yet again.
Beiden gecheckt, werkte allebei nog niet.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 9, 2016, 15:51

ben je toevallig in merc/

**Comment by thaliawww-service** [comment]
In GitLab by gerlings on Dec 9, 2016, 15:52

Ik ben 5 minuten geleden van Centraal Station vertrokken. Gaat hem niet meer worden voor maandag.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 9, 2016, 15:58

Ack. organisator is optioneel, dus je kunt het voor nu leeg laten.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 10, 2016, 12:07

Organisator is verplicht ;)

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 10, 2016, 12:18

En #211?

**Comment by thaliawww-service** [comment]
In GitLab by gerlings on Dec 10, 2016, 13:15

> Organisator is verplicht ;)
De eerstejaarscommissie gaat nog veel dingen organiseren als je de back-end moet geloven :'D
(works for now)

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 11, 2016, 16:51

```
Internal Server Error: /admin/events/event/add/
Traceback (most recent call last):
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1441, in changeform_view
    if form.is_valid():
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/forms/forms.py", line 169, in is_valid
    return self.is_bound and not self.errors
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/forms/forms.py", line 161, in errors
    self.full_clean()
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/forms/forms.py", line 370, in full_clean
    self._clean_fields()
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/forms/forms.py", line 388, in _clean_fields
    value = field.clean(value)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/forms/fields.py", line 158, in clean
    value = self.to_python(value)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/forms/models.py", line 1220, in to_python
    value = self.queryset.get(**{key: value})
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/db/models/query.py", line 389, in get
    (self.model._meta.object_name, num)
activemembers.models.MultipleObjectsReturned: get() returned more than one Committee -- it returned 2!
```
Gereproduceerd :tada:

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 11, 2016, 17:01

assigned to @se-bastiaan

**Comment by thaliawww-service** [comment]
In GitLab by gerlings on Dec 12, 2016, 11:20

Ik zit nog maar in één *onderwijscommissie* en nu werkt alles.

Hulde!

Was dit een manual fix en moet ik de issue laten staan of kan hij nu gesloten worden? (net zoals #211)
![2016-12-12-111754_582x146_scrot](https://gitlab.science.ru.nl//thalia/concrexit/uploads/3ecfe02d6280ab49b62de9ffeeb00304/2016-12-12-111754_582x146_scrot.png)

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 12, 2016, 18:36

Ik heb één van je commissielidmaatschappen verwijderd Frank, daardoor werkt het nu.

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 14, 2016, 19:45

closed via commit 8d4536e4a04d6639cf8048565e1d91636a98d2b3

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 14, 2016, 19:45

closed via merge request !245

**Comment by thaliawww-service** [comment]
In GitLab by @thomwiggers on Dec 14, 2016, 20:19

mentioned in commit 8d4536e4a04d6639cf8048565e1d91636a98d2b3
