### ISSUE TITLE
Object has no attribute 'name_None'

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#235]
In GitLab by @se-bastiaan on Dec 11, 2016, 16:45

Toen ik !246 aan het testen was kreeg ik opeens de onderstaande foutmelding. Het gekke: ik kreeg m niet nog een keer. Het leek me goed om m hier te posten.

Het doet me denken aan de exception die @joren485(?) en ik tegenkwamen binnen events, waarna ik translation.py aanpastte om dit te voorkomen en toen was niets meer vertaald. Dat is teruggedraaid, dus misschien is het dezelfde issue? Probleem is dus dat ik m nu niet nog een keer kreeg.

```
Traceback (most recent call last):
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 544, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/sites.py", line 211, in inner
    return view(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1512, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 1451, in changeform_view
    change_message = self.construct_change_message(request, form, formsets, add)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/contrib/admin/options.py", line 958, in construct_change_message
    'object': force_text(changed_object),
  File "/Users/Sebastiaan/Development/Thalia/concrexit/venv/lib/python3.5/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/website/activemembers/models.py", line 238, in __str__
    self.until)
  File "/Users/Sebastiaan/Development/Thalia/concrexit/website/activemembers/models.py", line 93, in __str__
    return self.name
  File "/Users/Sebastiaan/Development/Thalia/concrexit/website/utils/translation.py", line 59, in accessor
    return getattr(self, localize_attr_name(attr))
AttributeError: 'Committee' object has no attribute 'name_None'
```

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 14, 2016, 13:42

Bij het toevoegen van infofields aan events.

```
Traceback: 

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner 
39. response = get_response(request) 

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response 
187. response = self.process_exception_by_middleware(e, request) 

File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response 
185. response = wrapped_callback(request, *callback_args, **callback_kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in wrapper 
544. return self.admin_site.admin_view(view)(*args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view 
149. response = view_func(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/views/decorators/cache.py" in _wrapped_view_func 
57. response = view_func(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/sites.py" in inner 
211. return view(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in change_view 
1512. return self.changeform_view(request, object_id, form_url, extra_context) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapper 
67. return bound_func(*args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in _wrapped_view 
149. response = view_func(request, *args, **kwargs) 

File "/usr/local/lib/python3.5/site-packages/django/utils/decorators.py" in bound_func 
63. return func.__get__(self, type(self))(*args2, **kwargs2) 

File "/usr/local/lib/python3.5/contextlib.py" in inner 
30. return func(*args, **kwds) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in changeform_view 
1451. change_message = self.construct_change_message(request, form, formsets, add) 

File "/usr/local/lib/python3.5/site-packages/django/contrib/admin/options.py" in construct_change_message 
951. 'object': force_text(added_object), 

File "/usr/local/lib/python3.5/site-packages/django/utils/encoding.py" in force_text 
76. s = six.text_type(s) 

File "./events/models.py" in __str__ 
267. return "{} ({})".format(self.name, dict(self.FIELD_TYPES)[self.type]) 

File "./utils/translation.py" in accessor 
59. return getattr(self, localize_attr_name(attr)) 

Exception Type: AttributeError at /admin/events/event/147/change/ 
Exception Value: 'RegistrationInformationField' object has no attribute 'name_None' 
Request information: 
USER: sversteeg 
```

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 14, 2016, 14:32

1. Ga naar https://thalia.nu/admin/events/event/147/change/
2. Voeg een ‘Registration Information Field’ toe
3. Sla op

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 15, 2016, 16:11

Nog een:
1. Ga naar http://localhost:8000/admin/activemembers/committee/add/
2. Voeg een membership toe aan de comissie nadat je de rest hebt ingevuld
3. Sla op

Gewoon apart een lidmaatschap aanmaken lijkt wel te werken. Dus ik  heb het vermoeden dat dit iets met de inlines te maken heeft die worden gebruikt.

**Comment by thaliawww-service** [comment]
In GitLab by @lscholten on Dec 16, 2016, 23:29

Dit gaat fout bij het genereren van de change message met `construct_change_method` (ergens).
Deze roept de `__str__` aan van de classes, maar volgens deze meneer (https://code.djangoproject.com/ticket/27296) is er een decorator opgezet die de language op _None zet. Daardoor probeert hij `name_None` aan te roepen.

Een mogelijke (maar hele lelijke) oplossing zou zijn om wel `name_None` te registreren, maar deze aan de default language te koppelen. Misschien dat er in dat ticket nog wat meer uitleg staat waar wij ook gebruik van kunnen maken.

Edit: een search op  issues van de construct_change_message levert niet zo heel veel op helaas.
(https://code.djangoproject.com/query?status=assigned&status=closed&status=new&description=~construct_change_message&or&summary=~construct_change_message&desc=1&order=id)

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 17, 2016, 14:10

Zou het dan ook niet werken om in translations.py de default language te pakken áls de language `None` is? Dan hoeft je geen extra velden de registeren en werkt het waarschijnlijk wel?

**Comment by thaliawww-service** [comment]
In GitLab by @lscholten on Dec 17, 2016, 14:51

Dat is idd nog wat makkelijker, klinkt goed

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Dec 17, 2016, 17:17

In principe is er al zo'n check: https://gitlab.science.ru.nl/thalia/concrexit/blob/master/website/utils/translation.py#L51
Maar als de current language expliciet op `None` wordt gezet dan geeft `get_language` natuurlijk óók `None`. Dus moet er nog een fallback bij lijkt me.

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Dec 17, 2016, 17:58

@lscholten Met nog wat detail: 't gaat dus fout omdat er een Exception wordt aangemaakt (waarvan ik de inhoud niet ken), en bij 't schrijven van die Exception naar logs wordt de taalsetting expliciet genegeerd. Vervolgens is 't relevante object onderdeel van de foutmelding, en werkt die `__str__` niet (wat deze exception op de oorspronkelijke stapelt).

@se-bastiaan de bestaande check waar je naar verwijst is niet voor een scenario waarin de taal niet bekend is, maar is juist voor 't scenario waar je `get_language()` wil gebruiken om de taal van de gebruiker te achterhalen (voor gebruik in de accessor-functie, dus). Enfin, die is dus niet direct relevant, want zoals je aangeeft is `get_language()` in dit scenario inderdaad ook `None`

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Dec 17, 2016, 17:59

closed via commit 66752a2d76730d05b7dc569e9502a8f6e3f4c52f

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Dec 17, 2016, 17:59

closed via merge request !266

**Comment by thaliawww-service** [comment]
In GitLab by @joostrijneveld on Jan 11, 2017, 19:39

mentioned in commit 66752a2d76730d05b7dc569e9502a8f6e3f4c52f
