### ISSUE TITLE
Migrations fail on production data

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#612]
In GitLab by @joren485 on Mar 15, 2018, 14:24

When applying the migrations on production data (on `beta.thalia.nu`) the following error happens:

```
Operations to perform:
  Apply all migrations: activemembers, admin, announcements, auth, authtoken, contenttypes, documents, education, events, mailinglists, members, merchandise, newsletters, partners, payments, photos, pizzas, pushnotifications, registrations, sessions, sites, thabloid, thaliawebsite
Running migrations:
  Applying documents.0008_0_refactor_documents...Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: column "location_en" contains null values

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
...
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: column "location_en" contains null values
```

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 16, 2018, 13:03

How to reproduce:
1. `rm db.sqlite3`
2. `git checkout release/1.13`
3. `./manage.py migrate`
4. Create general meeting with location
4. `git checkout release/1.14`
3. `./manage.py migrate`
7. `IntegrityError: NOT NULL constraint failed: documents_generalmeeting.location_en`

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 16, 2018, 13:13

assigned to (at)tvbussel

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 20, 2018, 11:26

closed via merge request !765

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 20, 2018, 11:26

closed via commit e9b4c45a225ce037482d3716654482ba9ace01b7

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 20, 2018, 12:55

mentioned in commit 1052f471f7ebf9897ab442895d1207513ccf17ff

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Mar 20, 2018, 14:12

mentioned in commit e9b4c45a225ce037482d3716654482ba9ace01b7
