### ISSUE TITLE
Migration error during the release of v1.15.0

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#638]
In GitLab by @joren485 on May 23, 2018, 20:39

```
Applying thabloid.0004_regenerate_images...Traceback (most recent call last):
  File "./manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    fake_initial=fake_initial,
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 122, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 190, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/src/app/website/thabloid/migrations/0004_regenerate_images.py", line 7, in regenerate
    thabloid.extract_thabloid_pages(True)
AttributeError: 'Thabloid' object has no attribute 'extract_thabloid_pages'
```

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on May 23, 2018, 20:51

closed

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on May 23, 2018, 20:52

Run

```
# import thabloid.models.Thabloid
# for thabloid in Thabloid.objects.all(): thabloid.extract_thabloid_pages(True)
```
