### ISSUE TITLE
sendexpirationnotification.py crashed

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#674]
In GitLab by @joren485 on Aug 15, 2018, 12:31

### One-sentence description
`sendexpirationnotification.py` crashed while being run by `cron`.

### Current behaviour

```
Cron <root(at)virtueleivo> /var/docker-compose/concrexit/manage.py.sh sendexpirationnotification 2>&1 > /var/www/concrexit/log/cron_sendexpirationnotification.log
```

```
Traceback (most recent call last):
  File "/usr/src/app/website/manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/website/members/management/commands/sendexpirationnotification.py", line 18, in handle
    emails.send_expiration_announcement(bool(options['dry-run']))
  File "/usr/src/app/website/members/emails.py", line 90, in send_expiration_announcement
    with translation.override(member.language):
AttributeError: 'Member' object has no attribute 'language'
```

### Expected behaviour
No crash

### Steps to reproduce

1. run `sendexpirationnotification.py` command.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Aug 16, 2018, 08:44

closed via merge request !891

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Aug 16, 2018, 08:44

mentioned in commit f62b93da3dc2e0c39d7ea515cc10811f17bb6c24

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Aug 16, 2018, 08:44

mentioned in commit e1f503418db1ff86f9f8d804b1480c70c0e4891d
