### ISSUE TITLE
Vacancy fixture creation broken

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#698]
In GitLab by @thomwiggers on Sep 12, 2018, 16:31

### One-sentence description

```
./manage.py createfixtures -w 1 
Traceback (most recent call last):
  File "./manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/home/thom/.pythonenvs/concrexit-rWyBZ2S8/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/home/thom/.pythonenvs/concrexit-rWyBZ2S8/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/thom/.pythonenvs/concrexit-rWyBZ2S8/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/thom/.pythonenvs/concrexit-rWyBZ2S8/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/home/thom/git/thalia/concrexit/website/utils/management/commands/createfixtures.py", line 432, in handle
    self.create_vacancy(partners, categories)
  File "/home/thom/git/thalia/concrexit/website/utils/management/commands/createfixtures.py", line 362, in create_vacancy
    random.randint(0, 3))
  File "/home/thom/.pythonenvs/concrexit-rWyBZ2S8/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 509, in __set__
    % self._get_set_deprecation_msg_params(),
TypeError: Direct assignment to the forward side of a many-to-many set is prohibited. Use categories.set() instead.
```

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Oct 15, 2018, 13:11

mentioned in commit 86b6f45b25840785f966f22a5a150f74dd8b7151

**Comment by thaliawww-service** [comment]
In GitLab by @lukovdm on Oct 15, 2018, 13:11

closed via merge request !983
