### ISSUE TITLE
Pipenv is pinned to 18.0

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#718]
In GitLab by @joren485 on Oct 5, 2018, 15:08

### One-sentence description
The CI builds were failing

### Current behaviour
```
$ tox -e ${PYTHON_VERSION}-${DJANGO_VERSION}
py36-django20 create: /builds/thalia/concrexit/.tox/py36-django20
py36-django20 installdeps: pipenv
py36-django20 installed: certifi==2018.8.24,pipenv==2018.7.1,virtualenv==16.0.0,virtualenv-clone==0.3.0
py36-django20 runtests: PYTHONHASHSEED='2413802468'
py36-django20 runtests: commands[0] | pipenv --bare install --dev --ignore-pipfile
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
Installing dependencies from Pipfile.lock (731cb2)...
Traceback (most recent call last):
  File "/builds/thalia/concrexit/.tox/py36-django20/bin/pipenv", line 11, in <module>
    sys.exit(cli())
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/cli.py", line 435, in install
    selective_upgrade=selective_upgrade,
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/core.py", line 1943, in do_install
    pypi_mirror=pypi_mirror,
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/core.py", line 1322, in do_init
    pypi_mirror=pypi_mirror,
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/core.py", line 807, in do_install_dependencies
    pypi_mirror=pypi_mirror,
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/core.py", line 1375, in pip_install
    package_name.split('--hash')[0].split('--trusted-host')[0]
  File "/builds/thalia/concrexit/.tox/py36-django20/lib/python3.6/site-packages/pipenv/vendor/requirementslib/models/requirements.py", line 704, in from_line
    line, extras = _strip_extras(line)
TypeError: 'module' object is not callable
ERROR: InvocationError for command '/builds/thalia/concrexit/.tox/py36-django20/bin/pipenv --bare install --dev --ignore-pipfile' (exited with code 1)
```

### Expected behaviour
The builds work.

### Steps to reproduce

1. Create a pipeline.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Oct 5, 2018, 15:24

It's pipenv + pip: https://github.com/pypa/pipenv/issues/2924

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Oct 5, 2018, 15:57

Fixed in !982

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Oct 5, 2018, 15:57

closed

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Oct 5, 2018, 15:58

I'd like to keep this open until it's fixed upstream

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Oct 5, 2018, 15:58

reopened

**Comment by thaliawww-service** [comment]
In GitLab by @joren485 on Oct 5, 2018, 15:58

fair enough.

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Oct 12, 2018, 17:46

closed via merge request !993

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Oct 12, 2018, 17:46

mentioned in commit 875e67eedb020309a3f04a05203cb39bf8b26c4f
