### ISSUE TITLE
/usr/local/thalia/concrexit/manage.py.sh sync_mailinglists

### ISSUE THREAD

**Issue by thaliawww-service** [thaliawww/concrexit#950]
In GitLab by _thaliatechnicie on Nov 2, 2019, 11:46

Sentry Issue: [SERVER-2S](https://sentry.io/organizations/thalia/issues/1308881852/?referrer=gitlab_integration)

```
/usr/local/thalia/concrexit/manage.py.sh sync_mailinglists
--- Logging error ---
Traceback (most recent call last):
  File "/usr/src/app/website/mailinglists/gsuite.py", line 228, in _update_group_members
    memberKey=remove_member
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/googleapiclient/http.py", line 856, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://www.googleapis.com/admin/directory/v1/groups/apple%40thalia.nu/members/bestuur%40thalia.nu? returned "Resource Not Found: memberKey">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1025, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 869, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 608, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.7/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/usr/src/app/website/manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/src/app/website/mailinglists/management/commands/sync_mailinglists.py", line 16, in handle
    sync_service.sync_mailinglists()
  File "/usr/src/app/website/mailinglists/gsuite.py", line 316, in sync_mailinglists
    self.update_group(l.name, l)
  File "/usr/src/app/website/mailinglists/gsuite.py", line 116, in update_group
    self._update_group_members(group)
  File "/usr/src/app/website/mailinglists/gsuite.py", line 232, in _update_group_members
    f'{remove_member} from {group.name}', e.content)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1407, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/local/lib/python3.7/logging/__init__.py", line 1524, in handle
    self.callHandlers(record)
  File "/usr/local/lib/python3.7/site-packages/sentry_sdk/integrations/logging.py", line 78, in sentry_patched_callhandlers
    return old_callhandlers(self, record)
Message: 'Could not remove list member bestuur(at)thalia.nu from apple'
Arguments: (b'{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "notFound",\n    "message": "Resource Not Found: memberKey"\n   }\n  ],\n  "code": 404,\n  "message": "Resource Not Found: memberKey"\n }\n}\n',)

```

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Nov 3, 2019, 12:57

Read the error incorrect and this is just a 404

**Comment by thaliawww-service** [comment]
In GitLab by @se-bastiaan on Nov 3, 2019, 12:57

closed
